### ISSUE TITLE
Error after finished training

### ISSUE THREAD

**Issue by Husky110** [fumiama/Retrieval-based-Voice-Conversion-WebUI#10]
Hi - when I do a training on multiple GPUs (not sure if it does this on a single GPU aswell) there is an error on the sub-processes, which let the WebUI-Window display an error-message. As far as I can see this error does not really have any other consequences, but it would be nice to have it catched, so that the training-process looks much cleaner.  
Here are the logs:  
```
2024-06-07T11:43:12.483401697Z Process Process-2:
2024-06-07T11:43:12.485653172Z Traceback (most recent call last):
2024-06-07T11:43:12.485663442Z   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2024-06-07T11:43:12.485666154Z     self.run()
2024-06-07T11:43:12.485668107Z   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
2024-06-07T11:43:12.485670482Z     self._target(*self._args, **self._kwargs)
2024-06-07T11:43:12.485678737Z   File "/app/infer/modules/train/train.py", line 283, in run
2024-06-07T11:43:12.485691800Z     train_and_evaluate(
2024-06-07T11:43:12.485694025Z   File "/app/infer/modules/train/train.py", line 482, in train_and_evaluate
2024-06-07T11:43:12.485695903Z     scaler.scale(loss_disc).backward()
2024-06-07T11:43:12.485697369Z   File "/usr/local/lib/python3.10/site-packages/torch/_tensor.py", line 525, in backward
2024-06-07T11:43:12.485701996Z     torch.autograd.backward(
2024-06-07T11:43:12.485703833Z   File "/usr/local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 267, in backward
2024-06-07T11:43:12.485705673Z     _engine_run_backward(
2024-06-07T11:43:12.485707066Z   File "/usr/local/lib/python3.10/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
2024-06-07T11:43:12.485708666Z     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
2024-06-07T11:43:12.485710229Z RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [192.168.113.2]:11150
2024-06-07T11:43:12.487595588Z Process Process-3:
2024-06-07T11:43:12.490234611Z Traceback (most recent call last):
2024-06-07T11:43:12.490250554Z   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2024-06-07T11:43:12.490252622Z     self.run()
2024-06-07T11:43:12.490254034Z   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
2024-06-07T11:43:12.490255633Z     self._target(*self._args, **self._kwargs)
2024-06-07T11:43:12.490256844Z   File "/app/infer/modules/train/train.py", line 283, in run
2024-06-07T11:43:12.490258236Z     train_and_evaluate(
2024-06-07T11:43:12.490259604Z   File "/app/infer/modules/train/train.py", line 482, in train_and_evaluate
2024-06-07T11:43:12.490260992Z     scaler.scale(loss_disc).backward()
2024-06-07T11:43:12.490262255Z   File "/usr/local/lib/python3.10/site-packages/torch/_tensor.py", line 525, in backward
2024-06-07T11:43:12.490263779Z     torch.autograd.backward(
2024-06-07T11:43:12.490265122Z   File "/usr/local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 267, in backward
2024-06-07T11:43:12.490266643Z     _engine_run_backward(
2024-06-07T11:43:12.490267838Z   File "/usr/local/lib/python3.10/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
2024-06-07T11:43:12.490269376Z     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
2024-06-07T11:43:12.490271529Z RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [192.168.113.2]:11150
2024-06-07T11:43:16.854372502Z /usr/local/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 29 leaked semaphore objects to clean up at shutdown
2024-06-07T11:43:16.854419932Z   warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by fumiama** [comment]
The whole training script will be rewritten according to #8
